### ISSUE TITLE
Socketclient is no more functioning 

### ISSUE THREAD

**Issue by springmusk026** [kp7742/PUBGPatcher#3]
#springmusk

**Comment by ToshiroZ** [comment]
So you are a paster

**Comment by springmusk026** [comment]
> So you are a paster
 
 you are not a coder programmer or anything like that , you are a sucker just suck my eggs ,
 
 irrtiating useless bullshit

**Comment by DeveloperUmARx** [comment]
Take my dick in your asshole

**Comment by ToshiroZ** [comment]
> > So you are a paster
> 
> you are not a coder programmer or anything like that , you are a sucker just suck my eggs ,
> 
> irrtiating useless bullshit

Except for the fact I work for an authentication service
Make actual templates
And did something you can never recreate https://www.youtube.com/watch?v=w_BWiSSUh0w
Btw this video is older than your knowledge of ImGui
Keep stealing code from me 
Lord knows it's the only way you will get anywhere, paster.
